### ISSUE TITLE
WrikeProjectStatus enum missing value Custom.

### ISSUE THREAD

**Issue by Oozza** [staviloglu/Taviloglu.Wrike.ApiClient#14]
Taviloglu.Wrike.Core.FoldersAndProjects.WrikeProjectStatus enum is missing value Custom.

To reproduce:
1.  Use custom project workflow in Wrike
2.  Call FoldersAndProjects.GetFolderTreeAsync() method from code

NotFound exception will be thrown from inside JSON parser, indicating that value Custom does not exist in FoldersAndProjects.WrikeProjectStatus enum.

From wrike API documentation, project status enum should be:
Project status
Enum: Green, Yellow, Red, Completed, OnHold, Cancelled, Custom

**Comment by snaddenm** [comment]
I just logged in to report this issue too, but Oozza beat me to it. I have edited my local copy of ```private async Task<WrikeResDto<T>> SendRequest<T>()``` in WrikeClient.cs temporarily to detect this issue and modify the JSON before it is parsed to avoid the exception, but that's not a long-term solution.

**Comment by staviloglu** [comment]
Thanks @Oozza and @snaddenm.

Is anyone of you fixed the issue? 
If so, you can create a Pull Request and I can merge it and update the nuget package.

**Comment by snaddenm** [comment]
@staviloglu I'd like to try to submit a pull request for this to gain some experience. I'll clean up my fix and then try to create a pull request.

**Comment by snaddenm** [comment]
@staviloglu I have a local branch with a commit which fixes this (It's a one word change, the same as @Oozza suggested). Do you need to give me permission before I can push my new branch and create a pull request for it?

**Comment by staviloglu** [comment]
@snaddenm you should fork the library, make your changes there and than [create a PR from that fork.](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

**Comment by snaddenm** [comment]
@staviloglu thanks for encouraging me to learn how to do that. I created pull request 15.
https://github.com/staviloglu/Taviloglu.Wrike.ApiClient/pull/15

**Comment by staviloglu** [comment]
tx for the PR @snaddenm.
I'll need to update the core projects version and publish to nuget.

**Comment by franckies** [comment]
It would be nice to add also the custom status id to WrikeFolderTree.Project
