### ISSUE TITLE
"Multiple" missing from custom field type enumeration

### ISSUE THREAD

**Issue by snaddenm** [staviloglu/Taviloglu.Wrike.ApiClient#19]
The enumeration in the Wrike API for custom fields includes the "Multiple" type, but this value is not in the enumeration in the file WrikeCustomFieldTypes.cs. This causes an exception to be thrown by IWrikeCustomFieldsClient.GetAsync() if a custom field of this type is added to Wrike.

This can be fixed just by adding "Multiple" to the end of the enumeration. I'm about to submit a pull request.

**Comment by snaddenm** [comment]
I added Pull Request 20 for this.

**Comment by staviloglu** [comment]
[PR#20](https://github.com/staviloglu/Taviloglu.Wrike.ApiClient/pull/20) fixed this one
thx @snaddenm
