### ISSUE TITLE
Possible issue in CustomDateTimeConverter

### ISSUE THREAD

**Issue by tramperdk** [staviloglu/Taviloglu.Wrike.ApiClient#25]
#### Issue description
While trying to get tasks based on "**updatedDate**" a wrong format is returned by **CustomDateTimeConverter**.
I'm assuming this has something to do with my region settings or the like (Based in Denmark).

#### Steps to reproduce the issue
```csharp
DateTime start = DateTime.UtcNow.AddMilliseconds(-60000);
client.Tasks.GetAsync(updatedDate: new WrikeDateFilterRange(start,DateTime.UtcNow));
```

#### What's the expected result?
I expected the URI builder to format my dates as "2020-06-28T09:37:23Z" (Notice the colons in the time)

#### What's the actual result?
Dates are formatted with periods instead such as "2020-06-28T09.37.23Z"

#### Additional details / screenshot
![Screenshot](https://netsual.dk/img/dateformats.png)

**Comment by staviloglu** [comment]
Hi @tramperdk 
Thanks for reporting the issue.
I have tried reproduce the problem with the following code (console app with .NET Framework 4.6.1) but could not manage to get what you get when the dateTime value is serialized. Can you also run the code below to see if it behaves differently.

```csharp
using System;
using System.Threading;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public class Program
{
    public static void Main()
    {
        var culture = new System.Globalization.CultureInfo("da-DK");        
        Thread.CurrentThread.CurrentCulture = culture;
        Thread.CurrentThread.CurrentUICulture = culture;

        DateTime start = DateTime.UtcNow.AddMilliseconds(-60000);
        var rangeFilter = new WrikeDateFilterRange(start, DateTime.UtcNow);

        var serializedValue = JsonConvert.SerializeObject(rangeFilter, new CustomDateTimeConverter("yyyy-MM-dd'T'HH:mm:ss'Z'"));
        
        Console.WriteLine($"Current Culture is {Thread.CurrentThread.CurrentCulture}");
        
        Console.WriteLine(serializedValue);

        Console.Read();
    }
}

public class CustomDateTimeConverter : IsoDateTimeConverter
{
    public CustomDateTimeConverter(string format)
    {
        DateTimeFormat = format;
    }
}

/// <summary>
/// Timestamp semi-open interval
/// </summary>
public class WrikeDateFilterRange : IWrikeDateFilterRange
{
    /// <summary>
    /// Range start 
    /// </summary>
    [JsonProperty(PropertyName = "start",
        DefaultValueHandling = DefaultValueHandling.Ignore)]
    public DateTime Start { get; set; }

    /// <summary>
    /// Range end 
    /// </summary>
    [JsonProperty(PropertyName = "end",
        DefaultValueHandling = DefaultValueHandling.Ignore)]
    public DateTime End { get; set; }

    public WrikeDateFilterRange(DateTime start, DateTime end)
    {
        Start = start;
        End = end;
    }
}

public interface IWrikeDateFilterRange : IWrikeDateFilter
{
    DateTime Start { get; set; }
    DateTime End { get; set; }
}

public interface IWrikeDateFilter : IWrikeObject { }

public interface IWrikeObject {}
```

![image](https://user-images.githubusercontent.com/24274715/86510974-56459e00-bdfd-11ea-930d-61f52c09815e.png)

My Region settings are as follows and I don't see an opiton which represents the dateTime value with "."

![image](https://user-images.githubusercontent.com/24274715/86511027-edaaf100-bdfd-11ea-9472-8388f64941ea.png)

**Comment by staviloglu** [comment]
I get the same result when I change my regional format to denmark

![image](https://user-images.githubusercontent.com/24274715/86511110-92c5c980-bdfe-11ea-8e70-c2fd1437a0c3.png)

![image](https://user-images.githubusercontent.com/24274715/86511122-acffa780-bdfe-11ea-930b-1d732510a83f.png)

![image](https://user-images.githubusercontent.com/24274715/86511130-ba1c9680-bdfe-11ea-8334-add76146569e.png)

**Comment by tramperdk** [comment]
@staviloglu I'll check with your console app when I get back to work on Monday. Seems like it doesn't happen on my personal PC.
We'll get to the bottom of it 👍

**Comment by tramperdk** [comment]
@staviloglu new project and you code runs fine, so it seems to be some issue that I have in my project, that is not related to your code.

creating a DateTime object before the code also returns the dots instead of semicolon. 

After digging around a bit I see my `TimeSeparator` property of `CultureInfo.CurrentCulture.DateTimeFormat` is a `.`

I solved my problem by making my Thread "InvariantCulture" with `System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;`

I believe maybe the proper solution is to convert the DateTime with `CultureInfo.InvariantCulture` before sending it to the Wrike API.

**Comment by staviloglu** [comment]
@tramperdk thanks for the feedback. I think you are right that client should be changing the CurrentCulture to InvariantCulture before returning the string representation of a date value. This feature should be independent of the calling parties culture I guess.
