### ISSUE TITLE
Cannot change the author of a task

### ISSUE THREAD

**Issue by IsraelMarin** [staviloglu/Taviloglu.Wrike.ApiClient#28]
#### Issue description
When I create a task from any computer, it is always my user who is used as author. I tried to specify AuthorIds and my name still remains as author.

#### Steps to reproduce the issue

1.  Create a new WrikeTask
2. Check the author in wrike

#### What's the expected result?

-The name of the author should be the one specified in the AuthorIds

#### What's the actual result?

-It's always me whatever I specified in the AuthorsId

**Comment by staviloglu** [comment]
Hi @IsraelMarin thanks for sharing your problem.

Wrike [documentation ](https://developers.wrike.com/api/v4/tasks/#create-task) says that wrike returns only 1 authorId in authorIds field of the response.

Right now I can't see an option to set the authorId, the authorIds you set before create request is for the response not for the request. You can see that it's not used in request by checking the [code](https://github.com/staviloglu/Taviloglu.Wrike.ApiClient/blob/e42dda18a50a6c713df50d1ed3a9afc0907669fc/Taviloglu.Wrike.ApiClient/Tasks/WrikeClient.Tasks.cs#L35)

You only have the option to set sharedIds and the task is always shared with the author which is your user account using the client.

To achieve your goal, I guess you can try to creating different clients with different keys of the authors you want.

**Comment by IsraelMarin** [comment]
Hi @staviloglu thanks for your answer.

I'm currently testing it but believe it's because I'm using a permanent token and it's linked to my Wrike account. It would be for this reason that the tasks created by my application always have my account as creator.

I believe that if I would have used an "OAuth 2.0 authorization" token the creator would have been the logged in user.

Thank you for the .NET API and the support!!

**Comment by staviloglu** [comment]
@IsraelMarin thax again for sharing the issue which tells us we need an update so that user can not set the AuthorId of a task object, I might change it when I have time.
