### ISSUE TITLE
Default Colors

### ISSUE THREAD

**Issue by JCMonsalvo** [staviloglu/Taviloglu.Wrike.ApiClient#39]
#### Issue description
(Error converting value "DarkRed" to type 'Taviloglu.Wrike.Core.Colors.WrikeColor+CustomStatusColor'. Path 'data[2].customStatuses[0].color', line 147, position 28.)//Error converting value "DarkRed" to type 'Taviloglu.Wrike.Core.Colors.WrikeColor+CustomStatusColor'. Path 'data[2].customStatuses[0].color', line 147, position 28.//Requested value 'DarkRed' was not found.

#### Steps to reproduce the issue

1.  <wrike>.workflows.GetAsync()
2. 
3. 

#### What's the expected result?
Can Get any color in the new wrike UI 
-

#### What's the actual result?
Exception at deseriallize
-

#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by staviloglu** [comment]
@JCMonsalvo thanks for sharing the problem. This issue is fixed in Taviloglu.Wrike.Core v2.4.8 thanks to @heuristicAL
