### ISSUE TITLE
WrikeTask.OptionalFields Error

### ISSUE THREAD

**Issue by staviloglu** [staviloglu/Taviloglu.Wrike.ApiClient#4]
Wrike returns error if any other optional field used rather than AttachmentCount and Recurrent.
WrikeTask.OptionalFields should be reduced to only AttachmentCount and Recurrent.

**Comment by staviloglu** [comment]
IWrikeTasksClient.GetAsync(List<string> taskIds, List<string> optionalFields) is implemented to allow only those optional fields.

**Comment by shmulyeng** [comment]
Is there a reason only these optional fields are allowed? I need the ability to return all custom fields. I can make the change in my fork. I just want to know if there's anything specific to look out for.

**Comment by staviloglu** [comment]
Hi @shmulyeng. My first comment is six years old :) Don't know what the API returns today when other values are used. If you can test the API and make sure nothing fails, we can allow them.

**Comment by shmulyeng** [comment]
I didn't realize the other fields are returned by default for this call. There are some other available optional fields but I don't think they're implemented in the SDK.
