### ISSUE TITLE
Missing support for CustomItemTypeId on Tasks

### ISSUE THREAD

**Issue by mscc-sascha** [staviloglu/Taviloglu.Wrike.ApiClient#44]
#### Issue description
Wrike API does support as an optional field to return the property `customItemTypeId`. This is currently not supported in `WrikeClient.Tasks.cs`

#### Steps to reproduce the issue

1.  Try to get a task by calling `_wrikeTask = (await WrikeClient.Tasks.GetAsync(new List<string> { wrikeId }, optionalFields: new List<string> { "customItemTypeId" })).FirstOrDefault();` throws an exception with message `Only Recurrent, AttachmentCount and EffortAllocation is supported.`

#### What's the expected result?

- Return an instance of `WrikeTask` with the property `CustomItemTypeId` of type `string` set

**Comment by mscc-sascha** [comment]
@staviloglu I have implemented the solution for my reported issue, please see my open pull requests here: https://github.com/staviloglu/Taviloglu.Wrike.ApiClient/pull/45

**Comment by staviloglu** [comment]
issues is fixed in following packages;

Taviloglu.Wrike.Core.2.5.0
Taviloglu.Wrike.ApiClient.2.4.0
