### ISSUE TITLE
NextPageToken and ResponseSize fields

### ISSUE THREAD

**Issue by Bubu31** [staviloglu/Taviloglu.Wrike.ApiClient#5]
Hi,
First of all, thank you for your work !
I'm wondering how I could get the nextPageToken and responseSize fields.

We can easily add them in WrikeResDto <T> for serialization.

But as only the Data field is returned I do not really know how to recover them.

You have an idea ?

**Comment by staviloglu** [comment]
Hi @Bubu31 
Thanks for sharing your problem.
I did not think about this problem before, let me first investigate the code and wrike api to come up with a solution to discuss on.

**Comment by staviloglu** [comment]
Hi again @Bubu31 
I have added LastNextPageToken and LastResponseSize properties to TasksClient.
They can be used as examples below.
I think this solution is enough to close the issue, what do you say?

```cs
//example #1    
var pagedTaskList = await client.Tasks.GetAsync(pageSize: 20);
//you can read this property only after first paged request, otherwise it is 0
var responseSize = client.Tasks.LastResponseSize; 
//if you keep requesting with LastNextPageToken it will be empty when you get your last tasks of paged response
var nextPageToken = client.LastNextPageToken; 
while (!string.IsNullOrWhiteSpace(nextPageToken))
{
	pagedTaskList = await client.Tasks.GetAsync(nextPageToken: nextPageToken);
	nextPageToken = client.LastNextPageToken;
	//client.Tasks.LastResponseSize is zero here
}
```

```cs
//example #2
do
{
	var pagedList2 = await client.Tasks.GetAsync(nextPageToken:client.Tasks.LastNextPageToken, pageSize:20);
} while (!string.IsNullOrWhiteSpace(client.Tasks.LastNextPageToken));
```

**Comment by Bubu31** [comment]
Hi, is great ! 

Thank you !
