### ISSUE TITLE
Exception when calling CustomFields.GetAync() with field of type Users

### ISSUE THREAD

**Issue by snaddenm** [staviloglu/Taviloglu.Wrike.ApiClient#7]
This code has been working very well up to today. We added a new custom field in Wrike with type "Users" and started getting this exception:

`Error converting value "Contacts" to type 'Taviloglu.Wrike.Core.WrikeCustomFieldType`

The JSON from Wrike which triggers the problem is:

```JSON
{
  "kind": "customfields",
  "data": [
    {
      "id": "Deleted",
      "accountId": "Deleted",
      "title": "Task Owner",
      "type": "Contacts",
      "sharedIds": [],
      "settings": {
        "inheritanceType": "All"
      }
    }
  ]
}
```

The problem seems to be that "type" is set to "Contacts" in the JSON from Wrike while the ApiClient expects it to be set to "Users".

If I edit this code to change "Users" to "Contacts" then the exception does not happen and everything seems to work OK. I don't know what other consequences there might be from this change, for example when using the API to create a custom field.

```C#
namespace Taviloglu.Wrike.Core
{
    public enum WrikeCustomFieldType
    {
        Text,
        DropDown,
        Numeric,
        Percentage,
        Currency,
        Date,
        Duration,
        Checkbox,
        Users
    }
}
```

**Comment by staviloglu** [comment]
@snaddenm Thanks for tracking down the error and sharing it here. 
It seems to be the [wrike documentation for custom fields](https://developers.wrike.com/documentation/api/methods/query-custom-fields), which is the main ref. for the client development, is outdated.
Numeric > Numbers
Contacts > Users
As you mentioned WrikeCustomFieldType should be updated.

![wrikedocumentation](https://user-images.githubusercontent.com/24274715/43716445-d533b5f4-998c-11e8-8b04-58f2a1981dc0.JPG)

![wrikeui](https://user-images.githubusercontent.com/24274715/43716446-d551c7ce-998c-11e8-9a5c-6033c737ecac.JPG)

**Comment by staviloglu** [comment]
@snaddenm I was wrong in my previous comment that CustomFieldTypes are oudated in wrike documentation. 
I have updated the Taviloglu.Wrike.Core.WrikeCustomFieldType and changed Users to Contacts. 
Published the new nuget package [Taviloglu.Wrike.Core 0.90.0-alpha](https://www.nuget.org/packages/Taviloglu.Wrike.Core/0.90.0-alpha)
