### ISSUE TITLE
Timelogs/CustomFields value must not be empty Exception

### ISSUE THREAD

**Issue by Oozza** [staviloglu/Taviloglu.Wrike.ApiClient#8]
Getting Timelogs with empty comment results in "value must not be empty" exception
Getting CustomField with empty value also results in "value must not be empty" exception

In both cases, these values do not have to be filled in Wrike so it shouldn't throw exception, when they empty.

Validation that checks string is not empty is called in constructors of WrikeCustomFieldData and WrikeTimelogs respectively. I built library from source and commented out these calls, so I can continue using this library. 

Thanks for your work

**Comment by staviloglu** [comment]
Hi @Oozza thanks for sharing your problem. 

I can understand that for example when creating a Task you might want to add CustomFieldData with empty value, so you are absolutely right about that check needs to be removed from the ctor of the CustomFieldData.

The main idea behind the constructors ensuring that the values are not empty is that values (comment of Timelog and value of CustomFieldData) are used in POST requests to Wrike API and the API documentation says that they are not optional, at least for timelog
[Creating a timelog](https://developers.wrike.com/documentation/api/methods/create-timelog)

Can you share more information and maybe code to make clear why one may need to use empty Timelog without comment. I don't know if API accepts POST with empty comment.

**Comment by staviloglu** [comment]
The penny dropped :))

You may also want to log only the trackedDate and hours and not have any comment. 

Those constructors will change, thanks again for the warning.

**Comment by Oozza** [comment]
My use case is that I have to download Timelogs from Wrike. I am using GetAsync method and it throws exception, because some comments in Wrike were empty :)

**Comment by staviloglu** [comment]
@Oozza  I've updated the Core library you may check if its ok we can close this issue
